### PR TITLE
extended light source (Sun) with multi-threading + other minor updates to thermal model for spinup

### LINKED ISSUE #51: broken D.ndim == 2 option in shape.py
I think that while updating `shape.py` with the `is_occluded` function, the option for an extended light source (D.ndim == 2, with D the direction between the vector array to the "Sun") got broken.

The current `_is_occluded` doesn't work in either cgal or embree version. For the cgal version, the issue is visible at 

https://github.com/sampotter/python-flux/blob/700965ad79a8f387869459da433f63ad2629fe32/src/flux/shape.py#L263-L267

where `D[i]` cycles on the number of shape-model's facets instead of the number of "Sun facets/vectors" (in my case, D.shape=(100,3)).

For reference, see the old function `get_direct_irradiance` in the attached file (for a working embree version).
[shape.txt](https://github.com/sampotter/python-flux/files/7884830/shape.txt)

Any help is welcome @sampotter

### PR DESCRIPTION
**Pull request by steo85it**
As from the title, this contains the extension and improvements that we discussed yesterday about using an extended light source (with multi-threading of CGAL aabb), correcting the orientation of the imported mesh (current master has it upside down in stereo + too many steps), and some extension of the thermal model interface useful for the spinup+extended source.
Might be useful to merge this while the 2 branches haven't diverged. ;)
Would close #51.

### CODE REVIEW

**Comment by sampotter** [comment]
I skimmed it quickly. It looks it also includes a lot of changes to gerlache. I guess these are just the things you've been working on for your latest plots? Either way, looks good. Please go and merge.

**Comment by steo85it** [comment]
Yes, it includes the changes to gerlache for running the model over a full year and eventually spinning it up (that's anyway an additional script w.r.t. the equilibrium temperature ones). But also, yes, there are some modifications to `run_example.sh` that I could have avoid putting in there... anyway, that's really small and easy to change depending on needs.

**Comment by steo85it** [comment]
Oki, thanks! I hope most of it will be useful.

**Comment by steo85it** [comment]
Ops, sorry then, I'll keep it in mind (also, I'll try to make smaller and more focused pull requests...).
-------- Messaggio originale --------Da: Sam Potter ***@***.***> Data: 22/04/22  12:18 PM  (GMT-05:00) A: sampotter/python-flux ***@***.***> Cc: Stefano Bertone ***@***.***>, State change ***@***.***> Oggetto: Re: [sampotter/python-flux] extended light source (Sun) with multi-threading + other minor updates to thermal model for spinup (PR #64) 
I have been doing squash and merge, typically, but I haven't thought about which is preferable too much...

**Pull request merged**
