### PR TITLE
Hemisphere example

### PR DESCRIPTION
**Pull request by sampotter**
@steo85it @nschorgh

Here is the start of the "hemisphere example" (i.e. bowl-shaped crater).

Please take a quick look at this and then I will merge into master, at which point it can be run on a cluster somewhere.

In the two `collect_ingersoll_*.sh` scripts, the `$p` variable controls the fineness of the mesh. The larger the value, the finer the triangle mesh. I ran this for `p = 4, ..., 10` and got the following plots:

h_vs_assembly_time
h_vs_B_and_E_time
h_vs_rms
h_vs_size
h_vs_T_time

Here's the output when running `collect_ingersoll_stats.sh`:

```
p = 4
- groundtruth temperature in shadow: 148.86 K
- created tri. mesh with 244 faces
- wrote ingersoll.obj
- finished assembly (0.1 Mb) [0.60 s]
- wrote FF.bin
- computed direct irradiance [0.00 s]
- wrote E.png to disk
- computed radiosity [0.00 s]
- wrote B.png
- computed T [0.00 s]
- wrote T.png
- wrote error.png
- max error: 4.74 K
- RMS error: 1.47 K
- wrote stats.json

real	0m2.586s
user	0m8.008s
sys	0m0.415s

p = 5
- groundtruth temperature in shadow: 148.86 K
- created tri. mesh with 525 faces
- wrote ingersoll.obj
- finished assembly (0.2 Mb) [1.08 s]
- wrote FF.bin
- computed direct irradiance [0.00 s]
- wrote E.png to disk
- computed radiosity [0.01 s]
- wrote B.png
- computed T [0.01 s]
- wrote T.png
- wrote error.png
- max error: 2.70 K
- RMS error: 0.88 K
- wrote stats.json

real	0m2.667s
user	0m13.451s
sys	0m0.461s

p = 6
- groundtruth temperature in shadow: 148.86 K
- created tri. mesh with 1215 faces
- wrote ingersoll.obj
- finished assembly (0.8 Mb) [4.12 s]
- wrote FF.bin
- computed direct irradiance [0.00 s]
- wrote E.png to disk
- computed radiosity [0.01 s]
- wrote B.png
- computed T [0.01 s]
- wrote T.png
- wrote error.png
- max error: 2.23 K
- RMS error: 0.63 K
- wrote stats.json

real	0m5.808s
user	0m52.919s
sys	0m0.867s

p = 7
- groundtruth temperature in shadow: 148.86 K
- created tri. mesh with 2713 faces
- wrote ingersoll.obj
- finished assembly (1.5 Mb) [13.74 s]
- wrote FF.bin
- computed direct irradiance [0.01 s]
- wrote E.png to disk
- computed radiosity [0.01 s]
- wrote B.png
- computed T [0.03 s]
- wrote T.png
- wrote error.png
- max error: 1.70 K
- RMS error: 0.45 K
- wrote stats.json

real	0m15.505s
user	3m5.363s
sys	0m2.132s

p = 8
- groundtruth temperature in shadow: 148.86 K
- created tri. mesh with 6089 faces
- wrote ingersoll.obj
- finished assembly (4.4 Mb) [62.58 s]
- wrote FF.bin
- computed direct irradiance [0.02 s]
- wrote E.png to disk
- computed radiosity [0.03 s]
- wrote B.png
- computed T [0.09 s]
- wrote T.png
- wrote error.png
- max error: 1.27 K
- RMS error: 0.33 K
- wrote stats.json

real	1m4.763s
user	12m38.506s
sys	0m6.771s

p = 9
- groundtruth temperature in shadow: 148.86 K
- created tri. mesh with 13769 faces
- wrote ingersoll.obj
- finished assembly (11.9 Mb) [305.83 s]
- wrote FF.bin
- computed direct irradiance [0.03 s]
- wrote E.png to disk
- computed radiosity [0.04 s]
- wrote B.png
- computed T [0.12 s]
- wrote T.png
- wrote error.png
- max error: 1.01 K
- RMS error: 0.24 K
- wrote stats.json

real	5m8.230s
user	37m18.598s
sys	0m16.454s

p = 10
- groundtruth temperature in shadow: 148.86 K
- created tri. mesh with 30919 faces
- wrote ingersoll.obj
- finished assembly (33.6 Mb) [1610.97 s]
- wrote FF.bin
- computed direct irradiance [0.09 s]
- wrote E.png to disk
- computed radiosity [0.18 s]
- wrote B.png
- computed T [0.54 s]
- wrote T.png
- wrote error.png
- max error: 0.82 K
- RMS error: 0.19 K
- wrote stats.json

real	26m54.641s
user	122m6.081s
sys	0m41.162s
```

and the output of running `collect_ingersoll_gt_stats.sh`:

```
p = 4
- groundtruth temperature in shadow: 148.86 K
- created tri. mesh with 244 faces
- wrote ingersoll.obj
- tol argument not passed: assembling sparse form factor matrix
- finished assembly (0.1 Mb) [0.16 s]
- wrote FF.npz
- computed direct irradiance [0.00 s]
- wrote E.png to disk
- computed radiosity [0.00 s]
- wrote B.png
- computed T [0.00 s]
- wrote T.png
- wrote error.png
- max error: 4.74 K
- RMS error: 1.47 K
- wrote stats.json

real	0m1.814s
user	0m3.632s
sys	0m0.194s

p = 5
- groundtruth temperature in shadow: 148.86 K
- created tri. mesh with 525 faces
- wrote ingersoll.obj
- tol argument not passed: assembling sparse form factor matrix
- finished assembly (0.6 Mb) [0.59 s]
- wrote FF.npz
- computed direct irradiance [0.00 s]
- wrote E.png to disk
- computed radiosity [0.00 s]
- wrote B.png
- computed T [0.00 s]
- wrote T.png
- wrote error.png
- max error: 2.69 K
- RMS error: 0.87 K
- wrote stats.json

real	0m2.296s
user	0m9.408s
sys	0m0.305s

p = 6
- groundtruth temperature in shadow: 148.86 K
- created tri. mesh with 1215 faces
- wrote ingersoll.obj
- tol argument not passed: assembling sparse form factor matrix
- finished assembly (2.8 Mb) [2.42 s]
- wrote FF.npz
- computed direct irradiance [0.00 s]
- wrote E.png to disk
- computed radiosity [0.00 s]
- wrote B.png
- computed T [0.00 s]
- wrote T.png
- wrote error.png
- max error: 2.12 K
- RMS error: 0.65 K
- wrote stats.json

real	0m4.237s
user	0m36.584s
sys	0m0.441s

p = 7
- groundtruth temperature in shadow: 148.86 K
- created tri. mesh with 2713 faces
- wrote ingersoll.obj
- tol argument not passed: assembling sparse form factor matrix
- finished assembly (13.5 Mb) [11.46 s]
- wrote FF.npz
- computed direct irradiance [0.01 s]
- wrote E.png to disk
- computed radiosity [0.01 s]
- wrote B.png
- computed T [0.02 s]
- wrote T.png
- wrote error.png
- max error: 1.76 K
- RMS error: 0.46 K
- wrote stats.json

real	0m13.599s
user	2m51.475s
sys	0m0.958s

p = 8
- groundtruth temperature in shadow: 148.86 K
- created tri. mesh with 6089 faces
- wrote ingersoll.obj
- tol argument not passed: assembling sparse form factor matrix
- finished assembly (71.0 Mb) [54.14 s]
- wrote FF.npz
- computed direct irradiance [0.02 s]
- wrote E.png to disk
- computed radiosity [0.03 s]
- wrote B.png
- computed T [0.10 s]
- wrote T.png
- wrote error.png
- max error: 1.43 K
- RMS error: 0.34 K
- wrote stats.json

real	0m57.981s
user	7m2.509s
sys	0m3.499s

p = 9
- groundtruth temperature in shadow: 148.86 K
- created tri. mesh with 13769 faces
- wrote ingersoll.obj
- tol argument not passed: assembling sparse form factor matrix
- finished assembly (358.2 Mb) [258.76 s]
- wrote FF.npz
- computed direct irradiance [0.04 s]
- wrote E.png to disk
- computed radiosity [0.16 s]
- wrote B.png
- computed T [0.47 s]
- wrote T.png
- wrote error.png
- max error: 0.98 K
- RMS error: 0.24 K
- wrote stats.json

real	4m30.146s
user	21m33.088s
sys	0m7.933s

p = 10
- groundtruth temperature in shadow: 148.86 K
- created tri. mesh with 30919 faces
- wrote ingersoll.obj
- tol argument not passed: assembling sparse form factor matrix
- finished assembly (1836.2 Mb) [1381.31 s]
- wrote FF.npz
- computed direct irradiance [0.09 s]
- wrote E.png to disk
- computed radiosity [0.81 s]
- wrote B.png
- computed T [2.44 s]
- wrote T.png
- wrote error.png
- max error: 0.77 K
- RMS error: 0.19 K
- wrote stats.json

real	24m59.433s
user	71m37.929s
sys	0m18.806s
```

### CODE REVIEW

**Comment by steo85it** [comment]
Thanks @sampotter , this looks good for me. If it works with the latest changes, I should be able to easily run it on our cluster (up to max memory).

**Comment by sampotter** [comment]
Great, thanks. This is using the latest changes, so should be good.

I'll go ahead and merge this now. It would be helpful if you can find what the largest value of `$p` you can run the scripts with is. I am going to add some more stuff to these plots and then we can re-run the plots once for the biggest mesh size the cluster can accommodate.

**Comment by nschorgh** [comment]
* Comparison with results for the full uncompressed FF seems like a must.
* Hemispherical is misnomer. That crater has a diameter-to-depth ratio of more than 2:1. It could be called 'spherical' or 'bowl-shaped' crater.
* Since _h_ varies across the domain, _N_ might have a clearer meaning for the horizontal axis.

**Comment by nschorgh** [comment]
Equation (32) in our paper draft includes the temperatures for the sunlit portions, which should maybe also be included in the error.

**Comment by sampotter** [comment]
> * Comparison with results for the full uncompressed FF seems like a must.

This is already included. In the plots' legends the uncompressed FF matrix is referred to as "sparse FF" at the moment. This could be changed to "groundtruth FF" or something else.

>     * Hemispherical is misnomer. That crater has a diameter-to-depth ratio of more than 2:1. It could be called 'spherical' or 'bowl-shaped' crater.

Fixed this by changing "hemispherical" to "spherical".

>     * Since _h_ varies across the domain, _N_ might have a clearer meaning for the horizontal axis.

I'm not sure about this. But I can make both plots and we can see which seems more appropriate.

In the mean time, to give `h` a more consistent interpretation, I changed the way the mesh is refined: it will now refine the Delaunay triangulation until the area of each of the 3D triangles is no greater than some fixed maximum area (before it only considered the area of the 2D projection of these triangles). The difference between these two approaches isn't that significant.

> Equation (32) in our paper draft includes the temperatures for the sunlit portions, which should maybe also be included in the error.

Good point, but I actually don't think this is helpful to include. 

The difference between the sunlit region inside the crater and the shadowed region inside the crater is just the insolation. But the accuracy of the insolation is completely determined by the accuracy of the discretization of the radiosity integral equation (i.e. into piecewise constant basis functions on each triangle). That is, it has nothing to do with the error introduced by compressing the form factor matrix.

If we take the difference between the temperature in the sunlit portion of the crater between as computed using the groundtruth FF matrix and the compressed FF matrix, the two insolations will cancel and we will just end up with the same value as the temperature in the shadowed part of the crater.

We should mention this in the paper so that it's clear why we only need to look at the temperature in the shadowed region.

**Comment by nschorgh** [comment]
> > * Comparison with results for the full uncompressed FF seems like a must.
> 
> This is already included. In the plots' legends the uncompressed FF matrix is referred to as "sparse FF" at the moment. This could be changed to "groundtruth FF" or something else.

I understood 'sparse' to refer to using methods for sparse matrices. 'Full FF' might be unambiguous. 'Groundtruth' is something we can use for the temperature, but it's not a fitting term for the matrix. 

* Does it also converge in the maximum norm? Given the highly adaptive nature of the mesh, that would seem reasonable.

* For the convergence test one wants _h_ as figure label; and for the computing time one wants _N_.  One could go as far as having both as horizontal axis, one at the top and the other at the bottom.

**Pull request merged**
