### PR TITLE
additional option using uncompressed FF

### PR DESCRIPTION
**Pull request by steo85it**
Little mod to `examples/lsp_spice.py` to allow for the use of uncompressed FF (bool `compress` option).
As example, T_shadow for uncompressed FF (left) and compressed (right)
image

### CODE REVIEW

**Comment by nschorgh** [comment]
@steo85it  Thanks for the quick turnaround! Wouldn't this option better belong in `lsp_compress_form_factor_matrix.py` than in `lsp_spice.py`, because it performs shape_model -> FF ?

**Comment by steo85it** [comment]
No problem! I see your point, it's probably cleaner as you suggest, indeed. Let me change that.
In the meantime, I added a small routine which reads the "compressed" and "full" FF output (in terms of E and T) and plots the differences. Not sure if it should be a separate file, but it's probably convenient for testing.

**Comment by steo85it** [comment]
Actually, I think I have a better plan ... a small script calling the sequence of `examples/lsp_xxx.py`, with a `full/compressed FF` option and the plotting of differences. Should work fine and be reasonably clean.

**Comment by steo85it** [comment]
Ok, done! It works fine, but maybe `lsp_run.py` should directly be the `test` Sam was mentioning. 
Anyway, running `examples/lsp_run.py` goes through the whole chain: read .grd, get shape_model, compute both full and compressed FF, get T from both and compute/plot differences.

**Review by nschorgh — APPROVED** [review]
I haven't reviewed this in a meaningful way, but I look forward to running the programs after they are on the master branch.

**Comment by steo85it** [comment]
Merged! For sure there are improvements to be made, but it should be usable. :)

**Comment by nschorgh** [comment]
The compression artifacts for the bowl-shaped craters are small actually. There are scattered points on the plain, but almost no cross-artifact.

Temperature error uncompressed-analytical:
error-uncompressed-analystical

Temperature error compressed-analytical:
error-compressed-analytical

Temperature error compressed-uncompressed:
error-uncompressed-compressed

**Comment by steo85it** [comment]
Mmm, interesting. Did you limit the scale or is it correct to say that the differences between compressed vs uncompressed are at most of the same order as those between uncompressed vs analytical (and the cross/square artifacts even less prominent)? It would be interesting to check which ones of those differences can be attributed to an "excessive" truncation of the SVDs (e.g., are the spurious points outside also related to it?).

**Comment by nschorgh** [comment]
I did limit the scale to have the same range for all three figures, but the full max-min range of the errors isn't much larger.

Basically, the cross-artifact has disappeared, and I'm not sure when that happened. Maybe that was Sam's latest revision. But you're still seeing cross-artifacts it seems?

> It would be interesting to check which ones of those differences can be attributed to an "excessive" truncation of the SVDs (e.g., are the spurious points outside also related to it?).

How do I run this with less truncation?

**Comment by steo85it** [comment]
Well, it's much smaller than what you showed in earlier messages (a bit by memory), but errors/differences at the blocks level (which I called cross artifacts because the central one was the most visible in the first example) are still visible with the same signature of the "realistic example" at the lunar surface. Maybe something in the "ingersoll configuration" is particularly favorable to reduce/limit n-th order effects?

**Comment by steo85it** [comment]
> How do I run this with less truncation?

Good question ... besides playing around with `tol` (assuming it's now applied, after Sam's latest operations), I'm not sure. The `make_compressed_sparse_block` function in `flux/compressed_form_factors.py` seems to check if the `svd block` is good enough or whether to return the relevant `sparse block`, but nor there nor in `flux.linalg.estimate_rank` I could find a clear truncation step.

**Comment by sampotter** [comment]
(Just FYI, I have been paying attention to you guys' activity via email, but trying to let you handle things unless there is some serious need for me to help.)

See commit  https://github.com/sampotter/python-flux/commit/f6ee25edd09e868bc45a012014886f3ceccffb57 for my latest changes to truncation.

In particular, `flux.linalg.estimate_rank` is indeed what chooses the number of terms in the SVD. It does this adaptively. It computes a threshold (`thresh`) for the singular values, which comes from an error bound the approximate MVP should satisfy. This relates to the math behind the SVD, which I'm happy to explain, but will wait for you to ask me to do so before jumping in. :-) Basically, the threshold is a value which the smallest singular value in the truncated SVD should satisfy (recall that the singular values form a nonincreasing sequence). The function `estimate_rank` works by doubling the size of the SVD until this threshold is satisfied, and then keeping only the necessary terms. The commit I linked above mainly changed the way `thresh` was selected.

**Comment by steo85it** [comment]
+ checking that we don't mess up too much with "your baby". ;)
Thanks for the message, it makes things clearer: so now playing with the `tol` should indeed impact the SVD truncation (although not necessarily to the same number of terms for all blocks). And ok for point 3, good to keep in mind.

**Comment by nschorgh** [comment]
I played with changing the value of `k0` in `estimate_rank`, but it made no difference. And I'm already using `tol=0`. I can't get over the fact that it doesn't seem possible to get this method to compress less. If we could ameliorate the artifacts by compressing a bit less, we would be done.

**Comment by sampotter** [comment]
Changing the value of `k0` actually _shouldn't_ change anything. This parameter is just an "algorithmic detail": it's a good guess of an initial SVD size from which to start the doubling. Once a big enough `k` is found, the SVD will be shrunk back down to the smallest possible size which satisfies the threshold.

On the other hand, setting `tol = 0` and observing no different behavior is no good...

I think it would be a good idea to try using a debugger to step through and see what happens. Please check out [pdb](https://docs.python.org/3/library/pdb.html), Python's standard debugger. You can read more about how to use it if you follow that link, but it's pretty simple. Add the line:

```py
import pdb; pdb.set_trace()
```

where you want to start debugging. Run the code. When you drop into the debugger, it will have gdb-style commands (the usual `n`, `s`, `up`, `c`, etc. commands all work, and are fully explained in that link).

**Comment by nschorgh** [comment]
I'm not saying that changing `tol` wouldn't change the result, but what we need right now is *less* compression, the opposite of what a relaxed tolerance will do. Even tol=0 apparently truncates, somehow.

**Comment by sampotter** [comment]
We're on the same page, sorry if my reply is confusing. To clarify:

1. By design, changing `k0` shouldn't affect the output of ``estimate_rank,` only the time taken to compute it.
2. Changing `tol` _should_ affect the compression, and `tol = 0` is the most stringent choice (exact reconstruction).

I suggest trying a debugger to look into what's happening.

That said, there can still be truncation when `tol == 0`. This can happen when the matrix is truly low rank, which happens fairly often in our case. Typically in this case, we will select the original, uncompressed matrix, because it will typically be smaller in size than the compressed matrix (basically due to fill-in in the `U` and `V` matrices). When this happens, the MVPs of the compressed and uncompressed matrices should agree to machine precision.

**Comment by steo85it** [comment]
One could maybe patch the code to default to the sparse matrix if tol=0 ? It should be easy to do in `estimate_rank`.

    Il mercoledì 14 aprile 2021, 13:31:39 GMT-4, Sam Potter ***@***.***> ha scritto:  
 
 


We're on the same page, sorry if my reply is confusing. To clarify:
   
   - By design, changing k0 shouldn't affect the output of ``estimate_rank,` only the time taken to compute it.
   - Changing tol should affect the compression, and tol = 0 is the most stringent choice (exact reconstruction).

I suggest trying a debugger to look into what's happening.

That said, there can still be truncation when tol == 0. This can happen when the matrix is truly low rank, which happens fairly often in our case. Typically in this case, we will select the original, uncompressed matrix, because it will typically be smaller in size than the compressed matrix (basically due to fill-in in the U and V matrices). When this happens, the MVPs of the compressed and uncompressed matrices should agree to machine precision.

**Comment by sampotter** [comment]
I'm not sure if there are cases where `tol == 0` and the SVD results in a smaller matrix, but generally I agree this is probably a good idea. Although` if `tol == 0`, then probably no sense in using this approach, since right now `tol` is constant parameter.

**Comment by steo85it** [comment]
I agree, but it would be a way to introduce a "non-truncation" option and still use sparsity and other properties (unless the only compression resides in the svd truncation, then it indeed wouldn't make sense). It wouldn't help getting the opportunity to "compress a bit less" though.

**Comment by sampotter** [comment]
> I agree, but it would be a way to introduce a "non-truncation" option and still use sparsity and other properties (unless the only compression resides in the svd truncation, then it indeed wouldn't make sense). It wouldn't help getting the opportunity to "compress a bit less" though.

Currently the compression occurs as a result of using the SVD. This could happen even if `tol == 0`. For example, a matrix of all ones is rank 1, so that `estimate_rank` with `tol = 0` would return `k = 1`, indicating that the matrix can be represented exactly using a single term SVD (perfect accuracy + lots of compression).

For us, it is frequently the case that `estimate_rank` should return `k < min(m, n)` even if `tol = 0`. Why? Consider a sparse form factor matrix where there is a subset of rows and columns which contain only zero. Let `r` be the number of rows containing nonzero entries and `c` be the number of columns with nonzero entries. Then `k <= max(r, c)`. This can easily happen if there's lots of occlusion, especially when the sets of triangles are don't overlap. Basically, there is a nonzero submatrix to be extracted. Note that we can have `k < max(r, c)`: just imagine extending the matrix of all ones with zero rows and columns, and then maybe randomly permuting the rows and columns. The function `estimate_rank` should return `k = 1` even if `tol = 0` for this case.

(My claims above could also be checked by unit test. ;-) )
 
> > (@steo85it could be good to add unit tests validating these claims)
> 
> yes, it's on my list. I'm getting a bit crazy with raster masks and shapefile geometries with holes, in this beginning of week. ^^

Of course, not a problem. Just thought I would point it out since it occurred to me while I was writing my response. :-)

**Comment by steo85it** [comment]
Ok, I see your point. Then, I'd say it's not a good way to "separate" potential causes of the artifacts. We would need a way to avoid any truncation but still allow an SVD representation of the blocks.
(and sure, reminders are always good ;) )

**Comment by sampotter** [comment]
One simple thing to do would be to add an "oversampling parameter" to `estimate_rank`. Basically, add a keyword argument `q` (with `q=0` by default) which is just added to whatever the result of `estimate_rank` is (taking care to ensure that `k + q <= min(m, n)`). This is a pretty common strategy, and is done e.g. in [scipy's implementation ](https://docs.scipy.org/doc/scipy/reference/linalg.interpolative.html)of the [interpolative decomposition](https://en.wikipedia.org/wiki/Interpolative_decomposition) (the "ID"). The ID, incidentally, is an alternative to the SVD that is worth exploring at some point.

**Comment by steo85it** [comment]
always? Or only when `tol==0`?

**Comment by sampotter** [comment]
Always: `estimate_rank` searches for `k` as I described in my earlier reply, and then increases `k` by `q`. Typically `q` is pretty small, like `q = 8`. This will increase the size of the compressed matrix by a constant factor (ditto, it will slow down the MVPs by a constant factor), but should also increase the accuracy by a constant factor, if everything is working correctly.

**Pull request merged**
