### PR TITLE
MVP only for blocks with non-null/non-zero elements

### PR DESCRIPTION
**Pull request by steo85it**
Hi Sam,
here is the small change we discussed to speed-up the MVP by "ignoring/treating differently" the Zero and Null-blocks. It avoids creating several empty arrays (or np.zeros()) and then sum their elements, when the result is always 0.
It works, but there might be a more elegant way to write it. ;)

p.s.: sorry for the unforeseen .gitignore update ... I didn't realize that pull requests worked on a commit (and not on a file) basis.

### CODE REVIEW

**Comment by sampotter** [comment]
Hey Stefano,

Since you have a lot of different stuff in your PR (including GPU stuff, etc.), I thought I would just quickly implement your fix and push it.

Can you please check out 2389fb3b5f7de4308fbd885102ba25f728dea38d and tell me if it fixes the problem for you? (You can also see roughly how I would like to encode useful information like this into the different block classes in the object hierarchy.)

Sam

**Comment by steo85it** [comment]
Hi Sam,
I checked your changed version: it's a good idea to set an "empty_leaf" property, much cleaner, I'll keep that in mind. However, your more compact version doesn't take into account the case of a row of empty leaves within a block, that if not addressed properly results in an exception. That was the reason for the expanded for loop and the tmp array:
```
            if tmp != []:
                tmp = sum(tmp)
            else:
                **tmp = np.zeros((child.shape[0],1))**
            ys.append(tmp)
```
The bold line is needed to insert a 0 at the proper location in the ys array, so that dimensions are respected for the subsequent `return np.concatenate(ys)[self._row_rev_perm]`.
For sure it can be done in a more compact way than I did, but right now it is "a bit too compact"! :)

**Comment by sampotter** [comment]
Ah, thanks, good point!

I also like the idea to have an "is_empty_leaf" property rather than "is_nonempty_leaf" (less confusing...).

I made these changes and also fixed a small bug. Please try a0726cefc3ed60936a3b39ab8e8b9347ed11a175.

**Comment by steo85it** [comment]
Cool, thanks, I did not think about that solution!
As it is, though, sum raises an error `TypeError: sum() takes no keyword arguments`, which can be removed by removing the "start" keyword and just keeping the argument (that's a very weird, but sort of documented/known, behavior for the sum function, it seems).

**Comment by sampotter** [comment]
Weird, haven't run into that before. OK, I've gone ahead and fixed that in 4c7f367f0e7a0b0dd68f5cc083335d793397a888. Going to close this PR now.

**Pull request closed without merging**
